### ISSUE TITLE
loader - realms._base_ properties incorrectly overwrite realms properties of same name

### ISSUE THREAD

**Issue by jeremychone** [jeremychone/rust-kdd#1]
## Problem

Current the `realms._base_` properties incorrectly overwrite the realms properties of the same key name. It should be the other around (set `_base_` property only if realm does not have the key/value already)

For example: 
```yaml
realms:
  _base_:  
    ext_port: 8080
    web_server_replicas: 2

  dev:
    yaml_dir: k8s/dev/ 
    web_server_replicas: 4
```

- Expected result: 
  - `dev.ext_port = 8080` Because from `_base_`
  - `dev.web_server_replicas = 4` because we override
- Current Result
  - `dev.ext_port = 8080` OK
  - `dev.web_server_replicas = 2` WRONG should be 2

## Solution

Make sure `_base_` properties do not override realm properties.
